# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parser',
            new_name='ZipInfo',
        ),
    ]
